export const CREATE_TICKET_FAIL = 2;
export const CREATE_TICKET_SUCCESSFULLY = 1;
export const DELETE_TICKET_SUCCESSFULLY = 3;
export const DELETE_TICKET_FAIL = 4;

export const HOLD_SEAT_SUCCESSFULLY = 5;
export const GET_SEAT_SUCCESSFULLY = 6;
export const UNHOLD_SEAT_SUCCESSFULLY = 7;
export const BOUGHT_TICKET_SUCCESSFULLY = 8;
export const BOUGHT_TICKET_FAIL = 9;
export const CREATE_USER_SUCCESSFULLY = 10;
export const CREATE_USER_FAIL = 11;
export const SOMEONE_BOUGHT_TICKET_SUCCESSFULLY = 12;
export const PAYMENT_ORDER_SUCCESSFULLY = 13;
export const PAYMENT_ORDER_FAIL = 14;
export const SOMEONE_UN_BOUGHT_TICKET_SUCCESS = 15;
